export const messages = {
  alertHeading: 'Smart Retailer',
  unknownError: 'Something went wrong! We are working on it, please close the app and try again.',
  networkError: "Looks like you're not connected to internet, please connect and try again",
  NameEmpty: 'Name cannot be blank',
  GstEmpty: 'GSTIN cannot be blank',
  Address1Empty: 'Address 1 cannot be blank',
  Address2Empty: 'Address 2 cannot be blank',
  Address3Empty: 'Address 3 cannot be blank',
  CityEmpty: 'City cannot be blank',
  MobileEmpty: 'Mobile No. cannot be blank',
  MobileValidation: 'Mobile No. is invalid! Must have 10 numbers',
  WhatsappEmpty: 'Whatsapp No. cannot be blank',
  WhatsappValidation: 'Whatsapp No. is invalid! Must have 10 numbers',
  PasswordEmpty: 'Password cannot be blank',
  CpasswordEmpty: 'Confirm Password cannot be blank',
  CpasswordValidation: "Password Doesn't Match",
  registrationMsg: "Registration Successfull! OTP has being sent to your mobile no.",
  userVerify: "Your account is not verified! Please enter the OTP to Verify",
  paginationEndOfResults: "That's All for now",
  GumastaEmpty: "Gumasta Image is Required",
  GstUploadEmpty: "GST Document image is required",
  ShopEmpty: "Shop Image is Required",
  StreetEmpty: "Street Image is Required"
}
